PUT https://n8bpqsk91c.execute-api.eu-central-1.amazonaws.com/prod/pets
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer xxxxx

{
  "name": "111",
  "type": "aaa"
}
